//@COPYRIGHT@//
//
// Copyright (c) 2012, Tomoto S. Washio
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//   * Redistributions of source code must retain the above copyright
//     notice, this list of conditions and the following disclaimer.
//   * Redistributions in binary form must reproduce the above copyright
//     notice, this list of conditions and the following disclaimer in the
//     documentation and/or other materials provided with the distribution.
//   * Neither the name of the Tomoto S. Washio nor the names of his
//     contributors may be used to endorse or promote products derived from
//     this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL TOMOTO S. WASHIO BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//@COPYRIGHT@//

#ifndef _JOINT_H_
#define _JOINT_H_

#include "common.h"
#include "vec.h"

struct XuSkeletonJointInfo { float fConfidence; XV3 position; };

#ifdef XU_KINECTSDK

typedef NUI_SKELETON_POSITION_INDEX XuSkeletonJointIndex;

#define XU_SKEL_LEFT_SHOULDER NUI_SKELETON_POSITION_SHOULDER_LEFT
#define XU_SKEL_LEFT_ELBOW NUI_SKELETON_POSITION_ELBOW_LEFT
#define XU_SKEL_LEFT_HAND NUI_SKELETON_POSITION_HAND_LEFT
#define XU_SKEL_LEFT_HIP NUI_SKELETON_POSITION_HIP_LEFT
#define XU_SKEL_LEFT_KNEE NUI_SKELETON_POSITION_KNEE_LEFT
#define XU_SKEL_LEFT_FOOT NUI_SKELETON_POSITION_ANKLE_LEFT
#define XU_SKEL_RIGHT_SHOULDER NUI_SKELETON_POSITION_SHOULDER_RIGHT
#define XU_SKEL_RIGHT_ELBOW NUI_SKELETON_POSITION_ELBOW_RIGHT
#define XU_SKEL_RIGHT_HAND NUI_SKELETON_POSITION_HAND_RIGHT
#define XU_SKEL_RIGHT_HIP NUI_SKELETON_POSITION_HIP_RIGHT
#define XU_SKEL_RIGHT_KNEE NUI_SKELETON_POSITION_KNEE_RIGHT
#define XU_SKEL_RIGHT_FOOT NUI_SKELETON_POSITION_ANKLE_RIGHT
#define XU_SKEL_HEAD NUI_SKELETON_POSITION_HEAD
#define XU_SKEL_NECK NUI_SKELETON_POSITION_SHOULDER_CENTER
#define XU_SKEL_TORSO NUI_SKELETON_POSITION_SPINE
#define XU_SKEL_CENTER_SHOULDER NUI_SKELETON_POSITION_COUNT // needs special handling
#define XU_SKEL_JOINT_COUNT (NUI_SKELETON_POSITION_COUNT+1)

#elif XU_OPENNI2
typedef nite::JointType XuSkeletonJointIndex;

#define XU_SKEL_LEFT_SHOULDER nite::JOINT_LEFT_SHOULDER
#define XU_SKEL_LEFT_ELBOW nite::JOINT_LEFT_ELBOW
#define XU_SKEL_LEFT_HAND nite::JOINT_LEFT_HAND
#define XU_SKEL_LEFT_HIP nite::JOINT_LEFT_HIP
#define XU_SKEL_LEFT_KNEE nite::JOINT_LEFT_KNEE
#define XU_SKEL_LEFT_FOOT nite::JOINT_LEFT_FOOT
#define XU_SKEL_RIGHT_SHOULDER nite::JOINT_RIGHT_SHOULDER
#define XU_SKEL_RIGHT_ELBOW nite::JOINT_RIGHT_ELBOW
#define XU_SKEL_RIGHT_HAND nite::JOINT_RIGHT_HAND
#define XU_SKEL_RIGHT_HIP nite::JOINT_RIGHT_HIP
#define XU_SKEL_RIGHT_KNEE nite::JOINT_RIGHT_KNEE
#define XU_SKEL_RIGHT_FOOT nite::JOINT_RIGHT_FOOT
#define XU_SKEL_HEAD nite::JOINT_HEAD
#define XU_SKEL_NECK nite::JOINT_NECK
#define XU_SKEL_TORSO nite::JOINT_TORSO
#define XU_SKEL_CENTER_SHOULDER nite::JOINT_NECK // alias
#define XU_SKEL_JOINT_COUNT 15

#else // XU_OPENNI
typedef XnSkeletonJoint XuSkeletonJointIndex;

#define XU_SKEL_LEFT_SHOULDER XN_SKEL_LEFT_SHOULDER
#define XU_SKEL_LEFT_ELBOW XN_SKEL_LEFT_ELBOW
#define XU_SKEL_LEFT_HAND XN_SKEL_LEFT_HAND
#define XU_SKEL_LEFT_HIP XN_SKEL_LEFT_HIP
#define XU_SKEL_LEFT_KNEE XN_SKEL_LEFT_KNEE
#define XU_SKEL_LEFT_FOOT XN_SKEL_LEFT_FOOT
#define XU_SKEL_RIGHT_SHOULDER XN_SKEL_RIGHT_SHOULDER
#define XU_SKEL_RIGHT_ELBOW XN_SKEL_RIGHT_ELBOW
#define XU_SKEL_RIGHT_HAND XN_SKEL_RIGHT_HAND
#define XU_SKEL_RIGHT_HIP XN_SKEL_RIGHT_HIP
#define XU_SKEL_RIGHT_KNEE XN_SKEL_RIGHT_KNEE
#define XU_SKEL_RIGHT_FOOT XN_SKEL_RIGHT_FOOT
#define XU_SKEL_HEAD XN_SKEL_HEAD
#define XU_SKEL_NECK XN_SKEL_NECK
#define XU_SKEL_TORSO XN_SKEL_TORSO
#define XU_SKEL_CENTER_SHOULDER XN_SKEL_NECK // alias
#define XU_SKEL_JOINT_COUNT 25

#endif

#endif
